# Generated by Django 5.0.1 on 2024-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
