# Generated by Django 5.0.1 on 2024-02-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_review_user_review_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tour',
            new_name='product',
        ),
    ]
