# Generated by Django 5.0.1 on 2024-02-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='is_active',
        ),
    ]
